# Generated by Django 5.2.10 on 2026-01-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='family_contact',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
