# Generated by Django 5.2.10 on 2026-01-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_family_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('elderly', 'Elderly User'), ('caregiver', 'Caregiver'), ('family', 'Family Member'), ('doctor', 'Doctor')], default='elderly', max_length=20),
        ),
    ]
